
server:
  port: 8092

spring:
  application:
    name: service-commission
  datasource:
    url: jdbc:postgresql://localhost:5432/commission_db
    username: orleansgo
    password: orleansgo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
